### ISSUE TITLE
Suggestion for the documentation of Krylov.jl

### ISSUE THREAD

**Issue by amontoison** [tjdiamandis/RandomizedPreconditioners.jl#6]
Hi @tjdiamandis and @lukevolpatti!

I'm updating the documentation page about preconditioners today in Krylov.jl, and I would like to add one or two examples with RandomizedPreconditioners.jl.
Do you have any suggestions?

https://jso.dev/Krylov.jl/dev/preconditioners/#Examples

**Comment by tjdiamandis** [comment]
I think the example on the readme:

Given a positive semidefinite matrix `A`, we construct the Nyström Sketch `Â ≈ A` and then use the inverse of `P = Â + μ*I` as a preconditioner:
```julia
using RandomizedPreconditioners, Krylov
Â = NystromSketch(A, k, r)
Pinv = NystromPreconditionerInverse(Â, μ)
x, stats = cg(A+μ*I, b; M=Pinv)
```
where `μ`, `k`, and `r` are parameters with `k ≤ r`.

**Comment by amontoison** [comment]
Thanks @tjdiamandis for your quick answer!
I added the example tonight: https://github.com/JuliaSmoothOptimizers/Krylov.jl/pull/880

I also opened a PR to update the `README.md` here (#7).
Krylov.jl supports both `P` and `P⁻¹` now.
